name: BuyFly
main: Fly\Main
author: Kkora
description: "Turn on or off flight in survival mode"
version: 1.0.0
api: 2.0.0, 3.0.0, 4.0.0

commands:
 fly:
  usage: "/fly [player]"
  description: "Turn on or off flight in survival mode"
permissions:
  fly.me:
    default: op
    description: "Turn on or off flight in survival mode for yourself"
  fly.others:
    default: op
    description: "Turn on or off flight in survival mode for another player"
